"""Manifiesto de las 40 skills de marketing (adaptación v2)."""
from __future__ import annotations

from dataclasses import dataclass, field
from typing import Any


@dataclass(frozen=True)
class SkillRecord:
    slug: str
    template_key: str
    ctx: dict[str, Any] = field(default_factory=dict)
    summary_es: str = ""
    triggers_es: tuple[str, ...] = ()
    triggers_en: tuple[str, ...] = ()
    coord_category: str = "strategy"
    related_local: tuple[str, ...] = ()
    hooks_override: tuple[str, ...] | None = None


_SKILLS: list[SkillRecord] = [
    SkillRecord(
        slug="product-marketing-context",
        template_key="foundation",
        summary_es="Crea y mantiene el documento de contexto de marketing (producto, audiencia, posicionamiento) que el resto de skills debe leer primero.",
        triggers_es=("contexto de marketing", "ICP", "posicionamiento", "marketing-context.md", "antes de copy"),
        triggers_en=("marketing context", "ICP", "positioning", "set up context"),
        coord_category="foundation",
        related_local=("copywriting", "page-cro", "customer-research"),
    ),
    SkillRecord(
        slug="page-cro",
        template_key="cro_dual",
        ctx={
            "titulo": "CRO de página",
            "focus": "subir conversión en páginas clave (landing, pricing, features)",
            "ops_name": "page-cro-ops",
            "ops_path": "../../../jarvis/skills/page-cro-ops/SKILL.md",
        },
        summary_es="Diagnóstico y mejoras de conversión en páginas de marketing.",
        triggers_es=("optimizar landing", "subir conversión", "hero", "CTA"),
        triggers_en=("landing page", "conversion rate", "CRO"),
        coord_category="cro",
        related_local=("copywriting", "analytics-tracking", "ab-test-setup"),
    ),
    SkillRecord(
        slug="signup-flow-cro",
        template_key="cro",
        ctx={"titulo": "CRO del signup", "focus": "reducir fricción en registro/trial y mejorar activación inicial"},
        summary_es="Optimiza signup/registro/trial: mensajes, pasos y puntos de abandono.",
        triggers_es=("signup", "trial", "registro", "onboarding inicial"),
        triggers_en=("signup flow", "trial", "registration"),
        coord_category="cro",
        related_local=("onboarding-cro", "form-cro", "analytics-tracking"),
    ),
    SkillRecord(
        slug="onboarding-cro",
        template_key="cro",
        ctx={"titulo": "CRO de onboarding", "focus": "activación post-signup y time-to-value"},
        summary_es="Optimiza onboarding post-signup: primeros pasos, checklist y habit loops.",
        triggers_es=("activación", "primer uso", "setup wizard"),
        triggers_en=("activation", "onboarding", "aha moment"),
        coord_category="cro",
        related_local=("signup-flow-cro", "analytics-tracking"),
    ),
    SkillRecord(
        slug="form-cro",
        template_key="cro",
        ctx={"titulo": "CRO de formularios", "focus": "formularios de lead/contacto/demo sin ser signup"},
        summary_es="Optimiza formularios (lead, contacto, demo): campos, errores y microcopy.",
        triggers_es=("formulario", "lead form", "demo request"),
        triggers_en=("lead form", "contact form"),
        coord_category="cro",
        related_local=("page-cro", "copywriting"),
    ),
    SkillRecord(
        slug="popup-cro",
        template_key="cro",
        ctx={"titulo": "CRO de popups/modales", "focus": "overlays que convierten sin romper UX"},
        summary_es="Popups, modales y overlays orientados a captura o siguiente paso.",
        triggers_es=("popup", "modal", "overlay"),
        triggers_en=("popup", "modal"),
        coord_category="cro",
        related_local=("page-cro", "lead-magnets"),
    ),
    SkillRecord(
        slug="paywall-upgrade-cro",
        template_key="cro",
        ctx={"titulo": "CRO de paywall/upgrade", "focus": "paywalls, upgrades y gates de features"},
        summary_es="Paywalls, upgrades, upsells y feature gates in-app.",
        triggers_es=("paywall", "upgrade", "upsell", "pricing in-app"),
        triggers_en=("paywall", "upgrade", "upsell"),
        coord_category="cro",
        related_local=("pricing-strategy", "page-cro"),
    ),
    SkillRecord(
        slug="copywriting",
        template_key="copy_dual",
        ctx={"ops_path": "../../../jarvis/skills/copywriting-ops/SKILL.md", "ops_label": "copywriting-ops"},
        summary_es="Escribe copy persuasivo para páginas (hero, landing, pricing, features).",
        triggers_es=("landing copy", "hero", "pricing copy"),
        triggers_en=("copywriting", "landing page copy"),
        coord_category="copy",
        related_local=("copy-editing", "page-cro", "product-marketing-context"),
    ),
    SkillRecord(
        slug="copy-editing",
        template_key="copy",
        summary_es="Edita y pulimenta copy existente con foco en claridad y conversión.",
        triggers_es=("pulir texto", "editar copy", "claridad"),
        triggers_en=("copy editing", "rewrite"),
        coord_category="copy",
        related_local=("copywriting", "email-sequence"),
    ),
    SkillRecord(
        slug="cold-email",
        template_key="cold_dual",
        summary_es="Cold email B2B y secuencias cortas orientadas a respuesta.",
        triggers_es=("cold email", "prospección", "outreach"),
        triggers_en=("cold email", "outreach"),
        coord_category="copy",
        related_local=("email-sequence", "sales-enablement"),
    ),
    SkillRecord(
        slug="email-sequence",
        template_key="email_sequences",
        summary_es="Secuencias drip, lifecycle y automatizaciones de email.",
        triggers_es=("drip", "lifecycle email", "nutrición"),
        triggers_en=("email sequence", "drip"),
        coord_category="copy",
        related_local=("copywriting", "analytics-tracking"),
    ),
    SkillRecord(
        slug="social-content",
        template_key="pipeline_social",
        summary_es="Estrategia y piezas para redes (hooks, calendario, repurposing) enlazando pipeline jarvis.",
        triggers_es=("Instagram", "LinkedIn", "calendario editorial", "short-form"),
        triggers_en=("social content", "LinkedIn", "content calendar"),
        coord_category="pipeline",
        related_local=("copywriting", "image", "video", "page-cro"),
        hooks_override=(
            "`brand-kit` — validar identidad del dossier.",
            "`carousel-render` / `carousel-ops` — carruseles.",
            "`docs/CAROUSEL_PIPELINE_FREE.md`, `docs/REELS_TIKTOK_PIPELINE_FREE.md`.",
        ),
    ),
    SkillRecord(
        slug="image",
        template_key="pipeline_image",
        summary_es="Briefs y producción de imágenes de marketing enlazando render local e IA gratuita.",
        triggers_es=("hero image", "thumbnail", "creatividades estáticas"),
        triggers_en=("marketing image", "thumbnail"),
        coord_category="pipeline",
        related_local=("social-content", "copywriting", "page-cro"),
        hooks_override=(
            "`image-render`, `image-ai-free`, `carousel-render`, `brand-kit` (Tabla en marco de trabajo).",
        ),
    ),
    SkillRecord(
        slug="video",
        template_key="pipeline_video",
        summary_es="Guiones y pipeline de video corto con tts/subtitles/video-compose del ecosistema.",
        triggers_es=("reel", "video corto", "subtítulos"),
        triggers_en=("short video", "reel"),
        coord_category="pipeline",
        related_local=("social-content", "copywriting", "image"),
        hooks_override=(
            "`tts-free` → `subtitles` → `video-compose`; opcional `video-short`.",
        ),
    ),
    SkillRecord(
        slug="seo-audit",
        template_key="seo_dual",
        summary_es="Auditoría SEO técnica, on-page y de contenido con priorización accionable.",
        triggers_es=("auditoría SEO", "Search Console", "indexación"),
        triggers_en=("SEO audit", "technical SEO"),
        coord_category="seo",
        related_local=("ai-seo", "site-architecture", "schema-markup"),
    ),
    SkillRecord(
        slug="ai-seo",
        template_key="seo",
        ctx={"tema": "SEO para respuestas IA (AEO/GEO/LLMO)"},
        summary_es="Optimiza para motores de respuesta por IA y visibilidad en respuestas generadas.",
        triggers_es=("ChatGPT", "Perplexity", "visibilidad IA"),
        triggers_en=("AI SEO", "AEO", "GEO"),
        coord_category="seo",
        related_local=("seo-audit", "content-strategy"),
    ),
    SkillRecord(
        slug="programmatic-seo",
        template_key="seo",
        ctx={"tema": "SEO programático a escala"},
        summary_es="SEO programático con plantillas + datos estructurados y control de calidad.",
        triggers_es=("pSEO", "plantillas SEO", "datasets"),
        triggers_en=("programmatic SEO", "pSEO"),
        coord_category="seo",
        related_local=("site-architecture", "schema-markup"),
    ),
    SkillRecord(
        slug="site-architecture",
        template_key="seo",
        ctx={"tema": "Arquitectura de información y enlazado interno"},
        summary_es="Jerarquía de URLs, clusters temáticos y enlazado interno.",
        triggers_es=("estructura web", "silos", "internal linking"),
        triggers_en=("site architecture", "internal linking"),
        coord_category="seo",
        related_local=("content-strategy", "seo-audit"),
    ),
    SkillRecord(
        slug="competitor-alternatives",
        template_key="seo",
        ctx={"tema": "Páginas alternativas vs competencia"},
        summary_es="Páginas tipo \"alternativas a X\" para SEO y habilitación comercial.",
        triggers_es=("alternativas", "vs competidor", "comparativa"),
        triggers_en=("alternative pages", "vs competitor"),
        coord_category="seo",
        related_local=("competitor-profiling", "copywriting"),
    ),
    SkillRecord(
        slug="competitor-profiling",
        template_key="seo",
        ctx={"tema": "Investigación de competidores"},
        summary_es="Investiga y perfila competidores desde fuentes públicas con foco en mensajes y gaps.",
        triggers_es=("competencia", "benchmark", "landings rivales"),
        triggers_en=("competitor research", "competitive intel"),
        coord_category="research",
        related_local=("customer-research", "seo-audit"),
    ),
    SkillRecord(
        slug="schema-markup",
        template_key="seo",
        ctx={"tema": "Datos estructurados / Schema.org"},
        summary_es="Schema.org y datos estructurados para rich results.",
        triggers_es=("schema.org", "FAQ schema", "rich snippets"),
        triggers_en=("schema markup", "structured data"),
        coord_category="seo",
        related_local=("seo-audit", "site-architecture"),
    ),
    SkillRecord(
        slug="aso-audit",
        template_key="seo",
        ctx={"tema": "ASO (App Store / Google Play)"},
        summary_es="Audita y optimiza fichas de App Store / Google Play.",
        triggers_es=("ASO", "ficha app", "keywords móvil"),
        triggers_en=("ASO", "app store"),
        coord_category="seo",
        related_local=("analytics-tracking", "paid-ads"),
    ),
    SkillRecord(
        slug="paid-ads",
        template_key="paid",
        summary_es="Campañas pagadas: estructura de cuenta, creatividades y medición.",
        triggers_es=("Google Ads", "Meta Ads", "LinkedIn Ads"),
        triggers_en=("paid ads", "PPC"),
        coord_category="paid",
        related_local=("ad-creative", "analytics-tracking", "page-cro"),
    ),
    SkillRecord(
        slug="ad-creative",
        template_key="paid",
        summary_es="Itera creatividades publicitarias (titulares, textos, bundles creativos).",
        triggers_es=("creatividades", "variantes ads", "UGC brief"),
        triggers_en=("ad creative", "ads copy"),
        coord_category="paid",
        related_local=("paid-ads", "copywriting", "image"),
    ),
    SkillRecord(
        slug="directory-submissions",
        template_key="paid",
        summary_es="Planes de envío a directorios (startup/SaaS) con alcance y riesgos.",
        triggers_es=("directorios", "Product Hunt", "listados"),
        triggers_en=("directory submissions", "listings"),
        coord_category="growth",
        related_local=("seo-audit", "launch-strategy"),
    ),
    SkillRecord(
        slug="analytics-tracking",
        template_key="meas",
        summary_es="Define y audita medición: eventos, props, embudos y calidad de datos.",
        triggers_es=("GA4", "eventos", "data layer"),
        triggers_en=("analytics tracking", "events"),
        coord_category="meas",
        related_local=("ab-test-setup", "revops"),
    ),
    SkillRecord(
        slug="ab-test-setup",
        template_key="meas",
        summary_es="Diseña experimentos A/B y programas de experimentación continua.",
        triggers_es=("A/B test", "experimentación", "power analysis"),
        triggers_en=("A/B test", "experiment"),
        coord_category="meas",
        related_local=("page-cro", "analytics-tracking"),
    ),
    SkillRecord(
        slug="churn-prevention",
        template_key="retention",
        summary_es="Reduce churn: cancelación, save offers, dunning y recuperación de pagos.",
        triggers_es=("churn", "cancelación", "dunning"),
        triggers_en=("churn", "retention"),
        coord_category="retention",
        related_local=("pricing-strategy", "email-sequence"),
    ),
    SkillRecord(
        slug="free-tool-strategy",
        template_key="growth",
        summary_es="Evalúa/diseña free tools para marketing (lead gen, SEO, shares).",
        triggers_es=("free tool", "calculadora", "widget"),
        triggers_en=("free tool", "micro-product"),
        coord_category="growth",
        related_local=("lead-magnets", "seo-audit"),
    ),
    SkillRecord(
        slug="referral-program",
        template_key="growth",
        summary_es="Diseño y optimización de referidos / afiliados / word-of-mouth.",
        triggers_es=("referidos", "afiliados", "viral loop"),
        triggers_en=("referral program", "affiliate"),
        coord_category="growth",
        related_local=("revops", "analytics-tracking"),
    ),
    SkillRecord(
        slug="lead-magnets",
        template_key="growth",
        summary_es="Diseña lead magnets para captura y nutrición.",
        triggers_es=("lead magnet", "descargable", "checklist"),
        triggers_en=("lead magnet", "downloadable"),
        coord_category="growth",
        related_local=("email-sequence", "page-cro"),
    ),
    SkillRecord(
        slug="community-marketing",
        template_key="growth",
        summary_es="Construye y activa comunidades online para crecimiento y lealtad.",
        triggers_es=("Discord", "Slack community", "ambassadors"),
        triggers_en=("community marketing", "community-led"),
        coord_category="growth",
        related_local=("social-content", "referral-program"),
    ),
    SkillRecord(
        slug="marketing-ideas",
        template_key="strat_derived",
        ctx={"ops_label": "brainstorming-ops", "ops_path": "../../../jarvis/skills/brainstorming-ops/SKILL.md"},
        summary_es="Lluvia de ideas y tácticas para SaaS/software.",
        triggers_es=("ideas de marketing", "tácticas", "growth ideas"),
        triggers_en=("marketing ideas", "growth tactics"),
        coord_category="strategy",
        related_local=("launch-strategy", "content-strategy"),
    ),
    SkillRecord(
        slug="launch-strategy",
        template_key="strat_derived",
        ctx={"ops_label": "strategic-briefing-ops", "ops_path": "../../../jarvis/skills/strategic-briefing-ops/SKILL.md"},
        summary_es="Lanzamientos de producto/feature: mensajes, canales y timeline.",
        triggers_es=("lanzamiento", "go-to-market", "release"),
        triggers_en=("launch strategy", "GTM"),
        coord_category="strategy",
        related_local=("social-content", "paid-ads"),
    ),
    SkillRecord(
        slug="marketing-psychology",
        template_key="strat",
        ctx={"nombre": "Psicología de marketing"},
        summary_es="Principios psicológicos y modelos mentales aplicados a marketing.",
        triggers_es=("sesgos", "priming", "urgencia ética"),
        triggers_en=("marketing psychology", "behavioral"),
        coord_category="strategy",
        related_local=("copywriting", "pricing-strategy"),
    ),
    SkillRecord(
        slug="pricing-strategy",
        template_key="strat",
        ctx={"nombre": "Pricing y packaging"},
        summary_es="Pricing, packaging y monetización alineados a valor percibido.",
        triggers_es=("precios", "packaging", "descuentos"),
        triggers_en=("pricing strategy", "packaging"),
        coord_category="strategy",
        related_local=("paywall-upgrade-cro", "page-cro"),
    ),
    SkillRecord(
        slug="content-strategy",
        template_key="strat",
        ctx={"nombre": "Estrategia de contenidos"},
        summary_es="Define pilares temáticos, calendario y foco de negocio.",
        triggers_es=("editorial", "pilares SEO", "thought leadership"),
        triggers_en=("content strategy", "editorial"),
        coord_category="strategy",
        related_local=("seo-audit", "social-content"),
    ),
    SkillRecord(
        slug="revops",
        template_key="revops",
        summary_es="RevOps: etapas lead→cliente, scoring, routing marketing→ventas.",
        triggers_es=("pipeline CRM", "routing leads", "SLA"),
        triggers_en=("RevOps", "lead routing"),
        coord_category="strategy",
        related_local=("analytics-tracking", "sales-enablement"),
    ),
    SkillRecord(
        slug="sales-enablement",
        template_key="sales_derived",
        summary_es="Colateral comercial: decks, one-pagers, battlecards y objeciones.",
        triggers_es=("battlecard", "deck ventas", "one-pager"),
        triggers_en=("sales enablement", "battlecard"),
        coord_category="sales",
        related_local=("competitor-profiling", "customer-research"),
    ),
    SkillRecord(
        slug="customer-research",
        template_key="research_dual",
        summary_es="Investigación de clientes: entrevistas, VOC y JTBD con enlace a ops corta.",
        triggers_es=("entrevistas", "JTBD", "insights clientes"),
        triggers_en=("customer research", "JTBD"),
        coord_category="research",
        related_local=("product-marketing-context", "copywriting"),
    ),
]

SKILL_INDEX: dict[str, SkillRecord] = {s.slug: s for s in _SKILLS}


def all_slugs() -> list[str]:
    return [s.slug for s in _SKILLS]
